name: Tests

on: 
    push:
        branches: [ main ]

jobs:
    run_style_tests:
      runs-on: ubuntu-latest
      defaults:
         run:
            shell: bash -el {0}
      steps:
         - uses: actions/checkout@v2
         - uses: mamba-org/setup-micromamba@v1
           with:
               environment-file: etc/csci6118_env.yml
               environment-name: csci6118
         - run: |
            find . -name "*.py" -print0 | xargs -0 pycodestyle
            
    run_unit_tests:
      runs-on: ubuntu-latest
      defaults:
         run:
            shell: bash -el {0}
      steps:
         - uses: actions/checkout@v2
         - uses: mamba-org/setup-micromamba@v1
           with:
               environment-file: etc/csci6118_env.yml
               environment-name: csci6118
         - run: |
            cd test/unit
            python test_lkr_utils.py
            python test_sds_utils.py
            python test_jb_query_utils.py
            python test_gg_utils.py
            python test_gbq_utils.py
            
          
    run_func_tests:
      runs-on: ubuntu-latest
      defaults:
         run:
            shell: bash -el {0}
      steps:
         - uses: actions/checkout@v2
         - uses: mamba-org/setup-micromamba@v1
           with:
               environment-file: etc/csci6118_env.yml
               environment-name: csci6118
         - run: |
                cd test/func
                bash test_days_from_infection_plot.sh
                bash test_count.sh
                bash test_get_queried_data.sh
                bash test_plot_hist.bash
                bash test_prep_and_create_consort.sh
           